# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
    - repository: MyRepo
      type: github
      endpoint: github_1
      name: anukritigupta1234/helloworld
      

trigger:
- master

pool: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- checkout: MyRepo

"987e446e23ee0b75de203c4b1b00cb35c026625f"

typ_PipelineTriggerMaterializationRefTableV1
Deployment.tbl_PipelineTriggerMaterializationRef

Deployment.prc_GetPipelineTriggerMaterializationRef
prc_DeletePipelineTriggerMaterializationRef
prc_CreatePipelineTriggerMaterializationRef
DeploymentPipelineTriggerMaterialization
